spring.application.name: betterreads-data-loader

datadump.location:
    author: /Users/JSP/Spring & Spring Boot/betterreads/betterreads-data-loader/test-authors.txt
    works: /Users/JSP/Spring & Spring Boot/betterreads/betterreads-data-loader/test-works.txt

spring:
    data:
        cassandra:
            keyspace-name: main
            username: fqymCLKUCZyhNfEglWSsAexf
            password: vWd+75Jbf0JIl_nohHrZeMHDwvs,s5rFsr_56m0s12vEFsjeijmaq1,fsRBcklk6-MIN0z,0ibjmr78p_QuFv-GO.1GjJBu7qCksQ,M,NZirFrGR.w+Pj+79erDF0.3B
            schema-action: create-if-not-exists
            request:
                timeout: 10s
            connection:
                connect-timeout: 10s
                init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: 7cfddb4b-86c1-4769-8424-7f26f921d069-1
    region: us-west1
    keyspace: main
    application.token: AstraCS:fqymCLKUCZyhNfEglWSsAexf:a526f92949353bd758d72015d40bf30a00e41749723d7648c62acb94b95b8358

